version: "3.9"

services:
  postgres:
    container_name: postgresdb
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: example
    ports:
      - "5432:5432"
