// @generated by protoc-gen-connect-web v0.11.0 with parameter "target=ts,import_extension=none"
// @generated from file helloworld.proto (package jobManage, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateGroupRequest, CreateShiftRequest, CreateUserRequest, CreateUserResponse, GetAllGroupResponse, GetShiftsResponse, LoginUserRequest, LoginUserResponse } from "./helloworld_pb";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service jobManage.jobManageService
 */
export const jobManageService = {
  typeName: "jobManage.jobManageService",
  methods: {
    /**
     * @generated from rpc jobManage.jobManageService.createGroup
     */
    createGroup: {
      name: "createGroup",
      I: CreateGroupRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc jobManage.jobManageService.createUser
     */
    createUser: {
      name: "createUser",
      I: CreateUserRequest,
      O: CreateUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc jobManage.jobManageService.loginUser
     */
    loginUser: {
      name: "loginUser",
      I: LoginUserRequest,
      O: LoginUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc jobManage.jobManageService.createShift
     */
    createShift: {
      name: "createShift",
      I: CreateShiftRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc jobManage.jobManageService.getAllGroup
     */
    getAllGroup: {
      name: "getAllGroup",
      I: Empty,
      O: GetAllGroupResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc jobManage.jobManageService.getShifts
     */
    getShifts: {
      name: "getShifts",
      I: Empty,
      O: GetShiftsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

