//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "shift")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub shift_id: i32,
    pub user_id: i32,
    pub assigned: bool,
    pub start: DateTime,
    pub end: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
